# Generated by Django 3.2 on 2021-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='libelle',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
