# Generated by Django 3.2 on 2021-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('parent', models.CharField(blank=True, max_length=100)),
                ('direction_nom', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'direction',
                'verbose_name_plural': 'directions',
            },
        ),
    ]
