# Generated by Django 3.2 on 2021-04-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_alter_direction_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviation', models.CharField(max_length=50, unique=True)),
                ('alias', models.SlugField(max_length=100, unique=True)),
                ('service_nom', models.TextField(blank=True, max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direction.direction')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
    ]
